### ISSUE TITLE
Sharing images and labels used

### ISSUE THREAD

**Issue by ricardogffcouto** [kristiansyrjanen/billystat#2]
Hello all!

I am creating a similar project aiming to detect and track snooker balls using machine learning. Is it possible for you to share the images and labels used, so that the model is enriched by that data? :)

Thank you so much!

**Comment by kristiansyrjanen** [comment]
Hi @ricardogffcouto , unfortunately I've missed this issue completely.

I don't have the images/labels anywhere saved up anymore as this was something related to school project and I've changed computers in between so they must've lost during those times.

Just go to your local snooker club and photograph some snooker balls.

This project wasn't eventually even made using the material, but rather object recognition and colors.

\\Kristian
